services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ./tenancy_docs/index_docs/chroma_db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - net

  tenancy-docs:
    build:
      context: ./tenancy_docs
      dockerfile: Dockerfile
    container_name: tenancy-docs
    ports:
      - "4321:4321"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      - CHROMA_HOSTNAME=chromadb
    env_file:
      - ./tenancy_docs/api/.env
    command: poetry run gunicorn -b 0.0.0.0:4321 tenancy_docs.api.app:app
    depends_on:
      chromadb:
        condition: service_healthy
    networks:
      - net

  tenancy-app:
    container_name: tenancy-app
    build:
      context: ./tenancy_app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    depends_on:
      tenancy-docs:
        condition: service_healthy
    networks:
      - net

networks:
  net:
    driver: bridge
